version: 0.2

phases:
  pre_build:
    commands:
      - cd docker/gex_analysis/ && bash build.sh quay.io scrna_apps && cd ../../
  build:
    commands:
      - bash docker/gex_analysis/test.sh quay.io/gex_analysis
